const latestLectureData = {
    "title": "Chapter 1: An Overview of Cells and Cell Research (2025)",
    "professor": "김성찬",
    "summary": "2025년도 첫 강의입니다. 세포생물학의 가장 기본이 되는 개념들을 다루며, 앞으로 배울 모든 내용의 기초를 다집니다. 작년과 마찬가지로 '세포란 무엇인가'에서 시작하여 '어떻게 연구하는가'로 마무리되는 흐름은 동일합니다.<br><h4>🔑 핵심 암기 사항</h4><ul><li><strong>세포 이론(Cell Theory):</strong> 모든 생명체의 기본 단위는 세포이며, 세포는 기존 세포로부터만 생성된다는 기본 원리.</li><li><strong>원핵/진핵 구분:</strong> 막으로 둘러싸인 핵과 세포소기관의 유무가 핵심 차이점입니다. (<strong>Eukaryotic / Prokaryotic</strong>)</li></ul><div class=\"diagram\"><strong>DNA</strong><span class=\"arrow\">→ Transcription →</span><strong>RNA</strong><span class=\"arrow\">→ Translation →</span><strong>Protein</strong><br><small>(중심 원리 - Central Dogma)</small></div><p style=\"margin-top: 5px;\">* RNA에서 DNA로 가는 <strong>역전사(Reverse transcription)</strong> 과정도 매우 중요합니다.</p><h4><span class=\"text-red\">❗️ 기출 연관 중요 개념</span></h4><ul><li><strong>결합 조직(Connective tissue):</strong> 뼈(osteoblast), 연골(chondrocyte), 지방(adipocyte) 등을 포함합니다. <span class=\"text-red\">작년 1차 시험 출제!</span></li><li><strong>유도만능줄기세포(iPS cells):</strong> 성체 세포를 역분화시켜 만든 줄기세포. 정의를 묻는 문제가 <span class=\"text-red\">작년 1차 시험에 출제</span>되었습니다.</li></ul><h4>🧪 주요 연구 기법</h4><ul><li>세포 관찰을 위한 <strong>현미경(Microscopy)</strong>과 세포를 키우는 <strong>세포 배양(Cell culture)</strong>의 원리를 이해해야 합니다.</li></ul>",
    "reviewQuiz": [
        { "question": "A segment of DNA that is expressed to yield a functional product (e.g., a polypeptide or RNA molecule) is called a ____.", "source": "23년 1차 기출", "answer": "Gene (유전자)" },
        { "question": "성인의 체세포를 역분화시켜 배아줄기세포와 유사한 특성을 갖도록 만든 세포는 무엇인가요? (영문 약어)", "source": "23년 1차 기출", "answer": "iPS cells (유도만능줄기세포)" },
        { "question": "진핵세포와 원핵세포를 구분하는 가장 결정적인 구조적 차이점 한 가지를 서술하시오.", "source": "AI 예상 문제", "answer": "막으로 둘러싸인 핵(nucleus)의 유무입니다. 진핵세포는 핵이 있지만, 원핵세포는 핵이 없습니다." }
    ]
};

const lectureData = [
    { 
        "id": 1, 
        "date": "09/01", 
        "title": "Ch.1: An Overview of Cells and Cell Research", 
        "professor": "김성찬",
        "summary": "2025년도 첫 강의입니다. 세포생물학의 가장 기본이 되는 개념들을 다루며, 앞으로 배울 모든 내용의 기초를 다집니다. 작년과 마찬가지로 '세포란 무엇인가'에서 시작하여 '어떻게 연구하는가'로 마무리되는 흐름은 동일합니다.<br><h4>🔑 핵심 암기 사항</h4><ul><li><strong>세포 이론(Cell Theory):</strong> 모든 생명체는 세포로 이루어져 있으며, 세포는 기존 세포로부터만 생성된다는 기본 원리.</li><li><strong>원핵/진핵 구분:</strong> 막으로 둘러싸인 핵과 세포소기관의 유무가 핵심 차이점입니다. (<strong>Eukaryotic / Prokaryotic</strong>)</li></ul><div class=\"diagram\"><strong>DNA</strong><span class=\"arrow\">→ Transcription →</span><strong>RNA</strong><span class=\"arrow\">→ Translation →</span><strong>Protein</strong><br><small>(중심 원리 - Central Dogma)</small></div><p style=\"margin-top: 5px;\">* RNA에서 DNA로 가는 <strong>역전사(Reverse transcription)</strong> 과정도 매우 중요합니다.</p><h4><span class=\"text-red\">❗️ 기출 연관 중요 개념</span></h4><ul><li><strong>결합 조직(Connective tissue):</strong> 뼈(osteoblast), 연골(chondrocyte), 지방(adipocyte) 등을 포함합니다. <span class=\"text-red\">작년 1차 시험 출제!</span></li><li><strong>유도만능줄기세포(iPS cells):</strong> 성체 세포를 역분화시켜 만든 줄기세포. 정의를 묻는 문제가 <span class=\"text-red\">작년 1차 시험에 출제</span>되었습니다.</li></ul><h4>🧪 주요 연구 기법</h4><ul><li>세포 관찰을 위한 <strong>현미경(Microscopy)</strong>과 세포를 키우는 <strong>세포 배양(Cell culture)</strong>의 원리를 이해해야 합니다.</li></ul>" 
    },
    { 
        "id": 2, 
        "date": "09/03", 
        "title": "Ch.2: Molecules and Membrane", 
        "professor": "김재봉",
        "summary": "세포를 구성하는 분자와 세포막 구조를 배웁니다. 김재봉 교수님 파트는 **구조식을 직접 그리는 문제**가 출제되니 주의가 필요합니다.<br><h4>🔑 핵심 암기 사항</h4><ul><li><strong>4대 생체분자:</strong> 탄수화물, 지질, 단백질, 핵산의 기본 단위체와 중합체를 알아야 합니다.</li><li><strong>세포막:</strong> <strong>유동 모자이크 모델(Fluid Mosaic Model)</strong>이 핵심 개념입니다.</li></ul><h4><span class=\"text-red\">❗️ 기출 연관 중요 개념</span></h4><ul><li><strong>구조식 그리기:</strong> <span class=\"text-red\">23년 1차 시험</span>에서 **글루탐산(Glu), β-glucose, 포스파티딜세린(Phosphatidyl serine)**의 구조식을 직접 그리도록 출제되었습니다.</li><li><strong>중합체별 결합 종류:</strong> 단백질의 **펩타이드 결합(Peptide bond)**, 다당류의 **글리코사이드 결합(Glycosidic bond)** 등을 짝지어 외워야 합니다.</li></ul>"
    },
    { 
        "id": 3, 
        "date": "09/04", 
        "title": "Ch.3: Bioenergetics and Metabolism", 
        "professor": "김재봉", 
        "summary": "세포의 에너지 공장인 '물질대사'를 배우는 핵심 챕터입니다. 김재봉 교수님은 **각 과정의 특정 중간산물**을 묻는 단답형을 선호하시니, 큰 흐름과 함께 핵심 분자 이름을 암기하는 것이 중요합니다.<br><h4>🔑 핵심 암기 사항</h4><ul><li><strong>자유 에너지 (Gibbs Free Energy, ΔG):</strong> ΔG가 음수(-)일 때 반응이 저절로 일어난다는 기본 개념을 이해해야 합니다.</li><li><strong>ATP (Adenosine Triphosphate):</strong> 세포 활동에 직접 사용되는 '에너지 화폐'입니다.</li></ul><div class=\"diagram\"><strong>해당과정 (Glycolysis)</strong><span class=\"arrow\"> → </span><strong>TCA 회로 (Krebs Cycle)</strong><span class=\"arrow\"> → </span><strong>산화적 인산화</strong><br><small>(세포 호흡의 전체 흐름)</small></div><h4><span class=\"text-red\">❗️ 기출 연관 중요 개념</span></h4><ul><li><strong>TCA 회로의 첫 물질:</strong> <span class=\"text-red\">23년 1차 시험</span>에서 <strong>옥살아세트산(Oxaloacetate)</strong>과 <strong>아세틸 CoA</strong>가 만나 생성되는 첫 물질을 묻는 문제가 출제되었습니다. 정답은 <strong>시트르산(Citrate)</strong>입니다.</li><li><strong>전자전달계:</strong> 산화적 인산화 과정에서, 전자를 전달하며 양성자(H+)를 펌핑하는 복합체는 <strong>Complex I, III, IV</strong> 라는 것을 알아야 합니다. <span class=\"text-red\">(23년 1차 기출)</span></li></ul><h4>🧪 주요 용어</h4><ul><li><strong>기질 수준 인산화:</strong> 해당과정과 TCA 회로에서 소량의 ATP를 직접 만드는 방식.</li><li><strong>화학삼투:</strong> 산화적 인산화에서 양성자 기울기를 이용해 ATP를 대량 생산하는 원리.</li></ul>"
    },
    { "id": 4, "date": "09/08", "title": "Ch.4: Fundamentals of Molecular Biology", "professor": "김성찬", "summary": "분자생물학의 기본 원리를 다룹니다. DNA 구조, 유전자 발현의 기본 개념이 포함됩니다.<br><h4>🔑 핵심 암기 사항</h4><ul><li><strong>유전자(Gene):</strong> 기능적 산물(단백질 또는 RNA)을 만들어내는 DNA의 특정 구간. <span class=\"text-red\">23년 1차 기출</span></li><li><strong>역전사(Reverse transcription):</strong> RNA를 주형으로 DNA를 합성하는 과정. <strong>역전사효소(Reverse transcriptase)</strong>가 관여합니다. <span class=\"text-red\">23년 1차 기출</span></li></ul><h4><span class=\"text-red\">❗️ 기출 연관 중요 개념</span></h4><ul><li><strong>형질전환(Transfection):</strong> 동물 세포에 외부 DNA를 주입하는 기술. **리포솜(Liposomes)**이 운반체로 사용될 수 있습니다. <span class=\"text-red\">23년 1차 기출</span></li></ul>" },
    { "id": 5, "date": "09/11", "title": "Ch.5: Genomics", "professor": "김성찬", "summary": "유전체(Genome)의 구조와 구성을 배웁니다. 유전자 외 반복 서열의 중요성을 이해해야 합니다.<br><h4>🔑 핵심 암기 사항</h4><ul><li><strong>인트론(Intron)과 엑손(Exon):</strong> 진핵생물 유전자의 특징. 엑손이 실제 단백질 정보를 담고 있습니다.</li><li><strong>이동성 유전인자(Transposable elements):</strong> LINE, SINE과 같은 반복 서열로, 역전사를 통해 유전체 내에서 이동할 수 있습니다. <span class=\"text-red\">23년 1차 기출</span></li></ul>" },
    { "id": 6, "date": "09/15", "title": "Ch.5: Proteomics, and System Biology", "professor": "김성찬", "summary": "유전체(Genomics)를 넘어 단백질체(Proteomics)와 시스템 생물학을 다룹니다. 유전자 발현의 최종 산물인 단백질의 기능과 상호작용을 연구하는 학문입니다.<br><h4>🔑 핵심 암기 사항</h4><ul><li><strong>단백질체(Proteome):</strong> 한 세포 내에 존재하는 모든 단백질의 총합.</li><li><strong>시스템 생물학(System Biology):** 생명 현상을 개별 분자가 아닌, 전체 시스템의 상호작용으로 이해하려는 접근 방식입니다.</li></ul>" },
    { "id": 7, "date": "09/18", "title": "Ch.6: Genes and Genomes", "professor": "김성찬", "summary": "유전자와 유전체의 구조를 더 깊이 있게 배웁니다. 염색질(Chromatin)의 구조가 유전자 발현에 미치는 영향이 중요합니다.<br><h4>🔑 핵심 암기 사항</h4><ul><li><strong>유크로마틴(Euchromatin):</strong> 염색질이 풀려있어 유전자 전사가 활발한 영역. <span class=\"text-red\">23년 1차 기출</span></li><li><strong>헤테로크로마틴(Heterochromatin):</strong> 응축되어 있어 전사가 억제된 영역.</li><li><strong>텔로미어(Telomere):</strong> 염색체 말단을 보호하는 구조. <strong>텔로머레이스(Telomerase)</strong>에 의해 유지됩니다. <span class=\"text-red\">23년 1차 기출</span></li></ul>" },
    { "id": 8, "date": "09/24", "title": "Ch.7: DNA Replication and Repair", "professor": "이규영", "summary": "DNA 복제 과정과 손상된 DNA를 복구하는 기작을 배웁니다. 이규영 교수님은 5지선다 객관식으로 출제하시며, 과정에 관여하는 **효소와 단백질의 기능**을 정확히 아는 것이 중요합니다.<br><h4>🔑 핵심 암기 사항</h4><ul><li><strong>DNA 중합효소(DNA polymerase):</strong> 5'→3' 방향으로만 DNA를 합성하며, 시작을 위해 **프라이머(primer)**를 필요로 합니다. <span class=\"text-red\">23년 2차 기출</span></li><li><strong>Okazaki fragments:** 지연 가닥(Lagging strand)에서 생성되는 짧은 DNA 조각.</li></ul><h4><span class=\"text-red\">❗️ 기출 연관 중요 개념</span></h4><ul><li><strong>PCNA:** DNA 중합효소의 활성을 돕는 **슬라이딩 클램프(sliding clamp)** 역할을 합니다. <span class=\"text-red\">23년 2차 기출</span></li><li><strong>Mismatch Repair:** 복제 오류를 수정하는 기작. 이 시스템의 결함은 **유전성 비용종성 대장암(HNPCC)**을 유발합니다. <span class=\"text-red\">23년 2차 기출</span></li></ul>" },
    { "id": 9, "date": "09/25", "title": "Ch.7: DNA Rearrangements", "professor": "이규영", "summary": "유전체의 구조가 동적으로 변하는 유전자 재배열에 대해 배웁니다. 특히 면역계에서 항체의 다양성을 만드는 기작이 중요합니다.<br><h4>🔑 핵심 암기 사항</h4><ul><li><strong>상동 재조합(Homologous Recombination):** 유사한 염기서열 사이에서 일어나는 유전자 교환. DNA 이중나선 절단(double-strand break) 복구에 사용됩니다. <span class=\"text-red\">23년 2차 기출</span></li><li><strong>V(D)J 재조합:** 면역글로불린(항체) 유전자가 재배열되어 다양한 항체를 만드는 과정.</li></ul>" },
    { "id": 10, "date": "09/29", "title": "Ch.8: RNA synthesis (transcription)", "professor": "김재봉", "summary": "DNA 정보를 RNA로 옮겨 적는 과정인 전사(Transcription)를 배웁니다. 원핵생물의 lac 오페론 모델은 유전자 조절의 기본 원리이므로 반드시 이해해야 합니다.<br><h4>🔑 핵심 암기 사항</h4><ul><li><strong>RNA 중합효소(RNA polymerase):** DNA 중합효소와 달리 **프라이머(primer) 없이** 전사를 시작할 수 있습니다. <span class=\"text-red\">23년 2차 기출</span></li><li><strong>lac 오페론(lac operon):** 대장균의 젖당 분해 효소 유전자 조절 시스템. **억제자(repressor)**에 의한 음성 조절과 **CAP**에 의한 양성 조절이 모두 일어납니다. <span class=\"text-red\">23년 2차 기출</span></li></ul>" },
    { "id": 11, "date": "10/02", "title": "Ch.8: RNA processing", "professor": "김재봉", "summary": "진핵세포에서 전사된 RNA가 가공되는 과정을 배웁니다. 특히 mRNA의 스플라이싱(splicing)이 핵심입니다.<br><h4>🔑 핵심 암기 사항</h4><ul><li><strong>RNA 스플라이싱(Splicing):** 인트론(intron)은 제거되고 엑손(exon)만 연결되는 과정.</li><li><strong>대체 스플라이싱(Alternative splicing):** 하나의 유전자에서 다양한 조합의 엑손을 연결하여 여러 종류의 단백질을 만드는 기작. <span class=\"text-red\">23년 1차 기출(김성찬 교수님 파트)</span></li></ul>" },
    { "id": 12, "date": "10/13", "title": "Ch.9(10): Protein Synthesis (translation)", "professor": "조현주", "summary": "mRNA의 유전 정보를 읽어 단백질을 합성하는 번역(Translation) 과정을 배웁니다. 리보솜(Ribosome)의 구조와 기능, 그리고 tRNA의 역할이 중요합니다.<br><h4>🔑 핵심 암기 사항</h4><ul><li><strong>리보솜(Ribosome):** rRNA와 단백질로 구성된 번역 기계.</li><li><strong>tRNA:** 아미노산을 리보솜으로 운반하는 운반체 RNA.</li><li><strong>코돈(Codon)과 안티코돈(Anticodon):** mRNA의 3염기 조합인 코돈과 tRNA의 상보적인 안티코돈이 결합하여 아미노산을 지정합니다.</li></ul>" },
    { "id": 13, "date": "10/16", "title": "Ch.9(10): Regulation of Protein Fuction", "professor": "조현주", "summary": "단백질이 합성된 후, 그 기능이 어떻게 조절되는지를 배웁니다.<br><h4>🔑 핵심 암기 사항</h4><ul><li><strong>단백질 인산화(Phosphorylation):** 단백질의 활성을 조절하는 가장 대표적인 방식. **Protein kinase**가 인산기를 붙이고, **Protein phosphatase**가 떼어냅니다.</li><li><strong>유비퀴틴화(Ubiquitination):** **유비퀴틴(ubiquitin)**이라는 작은 단백질이 붙어 단백질 분해를 유도합니다. <span class=\"text-red\">23년 2차 기출</span></li></ul>" },
    { "id": 14, "date": "10/23", "title": "Ch.10(11): Nuclear Envelope", "professor": "이규영", "summary": "핵(Nucleus)의 구조, 특히 핵막과 핵공 복합체(Nuclear Pore Complex)를 통한 물질 수송을 배웁니다.<br><h4>🔑 핵심 암기 사항</h4><ul><li><strong>핵막(Nuclear Envelope):** 내막과 외막의 이중막 구조.</li><li><strong>핵공 복합체(Nuclear Pore Complex):** 핵과 세포질 사이의 선택적인 물질 이동 통로.</li><li><strong>Ran 단백질:** 핵-세포질 간 수송 방향성을 결정하는 GTP-결합 단백질. <span class=\"text-red\">23년 3차 기출</span></li></ul>" },
    { "id": 15, "date": "10/27", "title": "Ch.10(11): rRNA processing", "professor": "이규영", "summary": "리보솜의 구성 요소인 rRNA가 핵 안의 특정 구조인 인(Nucleolus)에서 어떻게 만들어지고 가공되는지를 배웁니다.<br><h4>🔑 핵심 암기 사항</h4><ul><li><strong>인(Nucleolus):** 막이 없는 구조로, rRNA의 전사와 가공, 리보솜 조립이 일어나는 공장. <span class=\"text-red\">23년 3차 기출</span></li><li><strong>rRNA 유전자:** 여러 복제본이 반복적으로 존재하며 **NOR(Nucleolar organizing region)**을 형성합니다.</li></ul>" },
    { "id": 16, "date": "10/30", "title": "Ch.11(12): Protein Sorting", "professor": "김성찬", "summary": "세포 내에서 합성된 단백질이 어떻게 정확한 목적지(세포소기관)로 배달되는지를 배웁니다. 특히 소포체(ER)를 통한 경로가 중요합니다.<br><h4>🔑 핵심 암기 사항</h4><ul><li><strong>소포체(ER)를 통한 경로:** 단백질이 ER → 골지체(Golgi)를 거쳐 최종 목적지로 이동하는 과정.</li><li><strong>최종 목적지:** 세포막(plasma membrane), 분비 소낭(secretory vesicle), 리소좀(lysosome). <span class=\"text-red\">23년 3차 기출</span></li></ul>" },
    { "id": 17, "date": "11/03", "title": "Ch.11(12): Protein Transport", "professor": "김성찬", "summary": "단백질 수송의 세부적인 기작, 특히 소낭(vesicle)을 이용한 수송을 배웁니다. 리소좀의 형성 과정은 서술형 문제로 자주 출제됩니다.<br><h4><span class=\"text-red\">❗️ 기출 연관 중요 개념</span></h4><ul><li><strong>리소좀(Lysosome) 형성 과정:** 세포 내 소화기관인 리소좀은 엔도솜(endosome) 경로를 통해 형성됩니다. **Mannose-6-phosphate**가 리소좀 효소를 골지체에서 후기 엔도솜으로 보내는 주소 역할을 합니다. <span class=\"text-red\">23년 3차 서술형 기출</span></li></ul>" },
    { "id": 18, "date": "11/05", "title": "Ch.12(13): Mitochondria/Peroxisomes", "professor": "김성찬", "summary": "세포의 발전소인 미토콘드리아와 해독 작용을 담당하는 퍼옥시솜의 구조와 기능을 배웁니다.<br><h4>🔑 핵심 암기 사항</h4><ul><li><strong>미토콘드리아(Mitochondria):** 세포 호흡과 ATP 생산의 중심. 내막과 외막의 이중막 구조를 가집니다.</li><li><strong>퍼옥시솜(Peroxisome):** 지방산 산화와 독성 물질 제거를 담당. 간세포에서 **담즙산(bile acids) 합성**에 관여합니다. <span class=\"text-red\">23년 3차 기출</span></li></ul>" },
    { "id": 19, "date": "11/06", "title": "Ch.13(14): Cytoskeleton", "professor": "조현주", "summary": "세포의 형태를 유지하고 움직임을 가능하게 하는 세포골격에 대해 배웁니다. 3종류의 필라멘트 특징을 비교하는 것이 중요합니다.<br><h4>🔑 핵심 암기 사항</h4><ul><li><strong>세포골격 3요소:** 액틴 필라멘트(Actin filament), 중간 필라멘트(Intermediate filament), 미세소관(Microtubule).</li><li><strong>항암제 Taxol:** 미세소관(Microtubule)을 안정화시켜 분해를 막음으로써, 세포 분열을 억제합니다. <span class=\"text-red\">23년 3차 기출</span></li></ul>" },
    { "id": 20, "date": "11/10", "title": "Ch.13(14): Cell Movement", "professor": "조현주", "summary": "세포골격이 어떻게 세포의 이동과 근육 수축을 일으키는지 배웁니다.<br><h4>🔑 핵심 암기 사항</h4><ul><li><strong>근육 수축:** 액틴(Actin)과 미오신(Myosin) 필라멘트의 상호작용(sliding)에 의해 일어납니다.</li><li><strong>세포 이동:** 세포 앞쪽에서 액틴 중합이 일어나고, 뒤쪽에서 수축이 일어나며 전진합니다.</li></ul>" },
    { "id": 21, "date": "11/12", "title": "Ch.14(15): Plasma Membrane-1", "professor": "조현주", "summary": "세포막의 구조와 물질 수송 기작을 더 자세히 배웁니다.<br><h4>🔑 핵심 암기 사항</h4><ul><li><strong>이온 채널(Ion Channel):** 특정 이온만 선택적으로 통과시키는 통로. 신경세포의 **활동 전위(Action potential)** 발생에 필수적입니다. <span class=\"text-red\">23년 3차 기출</span></li><li><strong>능동 수송(Active Transport):** ATP를 소모하여 농도 기울기를 거슬러 물질을 수송하는 방식. **Na+-K+ 펌프**가 대표적인 예입니다.</li></ul>" },
    { "id": 22, "date": "11/13", "title": "Ch.14(15): Plasma Membrane-2", "professor": "조현주", "summary": "세포가 외부의 큰 물질을 어떻게 세포 안으로 들여오는지(Endocytosis) 배웁니다.<br><h4>🔑 핵심 암기 사항</h4><ul><li><strong>식세포 작용(Phagocytosis):** 박테리아와 같은 큰 입자를 삼키는 과정. 대식세포(Macrophage)가 대표적입니다.</li><li><strong>클라트린-매개 내포작용(Clathrin-mediated endocytosis):** 특정 분자를 선택적으로 흡수하는 기작. **LDL 수용체**가 대표적인 예입니다.</li></ul>" },
    { "id": 23, "date": "11/19", "title": "Ch.15(16): Cell Wall", "professor": "조현주", "summary": "동물세포에는 없는, 식물과 세균의 세포벽 구조와 기능을 배웁니다.<br><h4>🔑 핵심 암기 사항</h4><ul><li><strong>세균 세포벽:** **펩티도글리칸(Peptidoglycan)**이 주성분. **페니실린**은 이 펩티도글리칸 합성을 억제하여 항균 작용을 합니다.</li><li><strong>식물 세포벽:** **셀룰로스(Cellulose)**가 주성분.</li></ul>" },
    { "id": 24, "date": "11/20", "title": "Ch.15(16): Cell Interaction", "professor": "조현주", "summary": "세포와 세포, 세포와 세포외기질(ECM) 사이의 상호작용을 배웁니다.<br><h4>🔑 핵심 암기 사항</h4><ul><li><strong>세포 부착 분자(CAMs):** Cadherin, Selectin, Integrin, Ig Superfamily.</li><li><strong>백혈구의 혈관 밖 이동(Extravasation):** **셀렉틴(Selectin)**과 **인테그린(Integrin)**의 순차적인 작용이 중요합니다. 카드헤린(Cadherin)은 관여하지 않습니다. <span class=\"text-red\">23년 4차 기출</span></li></ul>" },
    { "id": 25, "date": "11/24", "title": "Ch.16(17): Cell Signaling", "professor": "김재봉", "summary": "세포가 외부 신호를 어떻게 수용하고 내부로 전달하여 반응을 일으키는지, 즉 신호 전달 과정을 배웁니다. 양이 매우 많고 복잡한 챕터입니다.<br><h4>🔑 핵심 암기 사항</h4><ul><li><strong>수용체 종류:** 세포 내 수용체(Intracellular receptor)와 세포 표면 수용체(Cell surface receptor).</li><li><strong>세포 내 수용체 리간드:** 스테로이드 호르몬, 갑상선 호르몬 등 **소수성(hydrophobic) 분자**가 해당됩니다. <span class=\"text-red\">23년 4차 기출</span></li></ul>" },
    { "id": 26, "date": "11/26", "title": "Ch.16(17): Cell Signaling", "professor": "김재봉", "summary": "주요 신호 전달 경로인 GPCR과 Receptor Tyrosine Kinase 경로를 배웁니다.<br><h4><span class=\"text-red\">❗️ 기출 연관 중요 개념</span></h4><ul><li><strong>GPCR 경로:** G 단백질 → Adenylyl cyclase → cAMP → PKA로 이어지는 흐름을 알아야 합니다.</li><li><strong>RTK 경로:** 대표적인 예가 **Ras/Raf/MEK/ERK pathway**입니다. 이 경로의 순서를 묻는 문제가 <span class=\"text-red\">23년 4차 시험에 출제</span>되었습니다.</li></ul>" },
    { "id": 27, "date": "11/27", "title": "Ch.17(18): Cell Cycle", "professor": "이규영", "summary": "세포가 분열하고 증식하는 과정인 세포 주기를 배웁니다.<br><h4>🔑 핵심 암기 사항</h4><ul><li><strong>세포 주기 단계:** G1 → S (DNA 복제) → G2 → M (분열기) 순서로 진행됩니다. <span class=\"text-red\">23년 4차 기출</span></li><li><strong>주요 조절 인자:** **Cdk**와 **Cyclin** 복합체가 세포 주기의 각 단계를 조절하는 핵심 엔진입니다.</li></ul>" },
    { "id": 28, "date": "12/01", "title": "Ch.17(18): Cell Cycle", "professor": "이규영", "summary": "세포 주기의 각 단계가 올바르게 진행되는지 감시하는 점검 지점(Checkpoint)에 대해 배웁니다.<br><h4>🔑 핵심 암기 사항</h4><ul><li><strong>DNA 손상 점검 지점(DNA damage checkpoint):** DNA 손상이 감지되면 세포 주기를 멈추고 복구를 유도합니다. **p53** 단백질이 핵심적인 역할을 합니다.</li></ul>" },
    { "id": 29, "date": "12/03", "title": "Ch.18(19): Cell Death", "professor": "김재봉", "summary": "세포가 스스로 사멸하는 과정인 프로그램된 세포 사멸(Apoptosis)을 배웁니다.<br><h4>🔑 핵심 암기 사항</h4><ul><li><strong>아폽토시스(Apoptosis):** 세포가 수축하고, 염색질이 응축되며, 세포가 작은 조각으로 나뉘는 등 질서정연한 과정을 통해 죽는 방식.</li><li><strong>캐스페이스(Caspase):** 아óp토시스를 실행하는 핵심적인 단백질 분해 효소.</li></ul>" },
    { "id": 30, "date": "12/04", "title": "Ch.18(19): Cell Renewal", "professor": "김재봉", "summary": "조직을 유지하고 복구하는 줄기세포(Stem cell)의 역할에 대해 배웁니다.<br><h4>🔑 핵심 암기 사항</h4><ul><li><strong>줄기세포(Stem cell)의 2가지 특성:**** 스스로를 복제하는 능력(Self-renewal)과 여러 종류의 세포로 분화할 수 있는 능력(Differentiation).</li></ul>" },
    { "id": 31, "date": "12/08", "title": "Ch.19(20): Cancer", "professor": "이규영", "summary": "세포 주기의 조절이 망가져 발생하는 질병인 암에 대해 배웁니다.<br><h4>🔑 핵심 암기 사항</h4><ul><li><strong>암의 종류:** 상피세포 유래의 **암종(Carcinomas)**, 결합조직 유래의 **육종(Sarcomas)**, 혈액세포 유래의 **백혈병/림프종(Leukemias/Lymphomas)**. <span class=\"text-red\">23년 4차 기출</span></li><li><strong>암 유전자:** 정상 세포의 증식을 촉진하는 **원종양유전자(Proto-oncogenes)**와 암 발생을 억제하는 **종양억제유전자(Tumor suppressor genes)**.</li></ul>" }
];

const questionData = [
    { "id": 101, "chapter": [4], "professor": "김성찬", "exam": "1차", "question": "A ( ) segment of DNA that is expressed to yield a functional product. (e.g., rRNA, tRNA or a polypeptide)", "answer": "gene" },
    { "id": 102, "chapter": [1], "professor": "김성찬", "exam": "1차", "question": "( ) include bone(osteoblast), cartilage(chondrocyte), and adipose (adipocyte) tissue.", "answer": "Connective tissue" },
    { "id": 103, "chapter": [1], "professor": "김성찬", "exam": "1차", "question": "() are a type of pluripotent stem cell derived from adult somatic cells...", "answer": "IPS (induced pluripotent stem cells)" },
    { "id": 104, "chapter": [4], "professor": "김성찬", "exam": "1차", "question": "() is the synthesis of DNA from RNA. ( ) is enzyme used to generate cDNA from RNA template.", "answer": "Reverse transcription, Reverse transcriptase" },
    { "id": 105, "chapter": [4], "professor": "김성찬", "exam": "1차", "question": "() is a method for introducing DNA into animal cells. ( ) are lipid vesicles...", "answer": "Transfection, Liposomes" },
    { "id": 106, "chapter": [5, 8], "professor": "김성찬", "exam": "1차", "question": "( ) that control transcription of a gene may be located up to hundreds of kilobases away...", "answer": "Transcription Regulatory Elements" },
    { "id": 107, "chapter": [8], "professor": "김성찬", "exam": "1차", "question": "() occurs when exons of a gene are joined in different combinations...", "answer": "Alternative splicing" },
    { "id": 108, "chapter": [5], "professor": "김성찬", "exam": "1차", "question": "() and ( ) are transposable elements... Both are retrotransposons...", "answer": "LINE, SINE" },
    { "id": 201, "chapter": [2], "professor": "김재봉", "exam": "1차", "question": "Glu의 구조식을 그리시오.", "answer": "Glutamic acid (Glu) E..." },
    { "id": 202, "chapter": [2], "professor": "김재봉", "exam": "1차", "question": "β-glucose의 구조식을 그리시오.", "answer": "β-D-glucose의 고리 구조..." },
    { "id": 203, "chapter": [2], "professor": "김재봉", "exam": "1차", "question": "phosphatidyl serine의 구조식을 그리시오.", "answer": "글리세롤 골격에 두 개의 지방산과 인산기가 결합..." },
    { "id": 204, "chapter": [3], "professor": "김재봉", "exam": "1차", "question": "α-ketoglutarate의 구조식을 그리시오.", "answer": "5탄소 디카르복실산으로, 2번 탄소에 케톤 그룹..." },
    { "id": 205, "chapter": [2], "professor": "김재봉", "exam": "1차", "question": "주로 수소결합(hydrogen bond)을 사용하여 분자의 안정성을 높이는 우리 몸을 구성하는 핵심물질 3가지를 적으시오.", "answer": "물(water), 단백질(protein), 핵산(nucleic acid)" },
    { "id": 301, "chapter": [7, 8], "professor": "김재봉", "exam": "2차", "question": "DNA polymerase와 RNA polymerase의 공통된 성질 두 가지와 서로 다른 특이적 성격은 무엇인가?", "answer": "공통점: 1. 5'->3' 합성, 2. DNA template 필요..." },
    { "id": 302, "chapter": [8], "professor": "김재봉", "exam": "2차", "question": "lac operon에서 negative control과 positive control은 그 조절을 관여하는 (a)에 의해 결정된다...", "answer": "Negative control: repressor, allolactose..." },
    { "id": 401, "chapter": [10], "professor": "박재봉", "exam": "2차", "question": "단백질 분해를 조절하는 단백질은 무엇인가?", "answer": "4. ubiquitin" },
    { "id": 402, "chapter": [10, 17], "professor": "박재봉", "exam": "2차", "question": "단백질 인산화와 가장 거리가 먼 것은?", "answer": "5. lysine..." },
    { "id": 501, "chapter": [7], "professor": "이규영", "exam": "2차", "question": "DNA 복제에 관해 옳은 것은?", "answer": "4. leading strand와 lagging strand 모두 DNA 합성을 위해 primer strand를 필요로 한다." },
    { "id": 502, "chapter": [7], "professor": "이규영", "exam": "2차", "question": "PCNA의 역할로 알맞은 것은?", "answer": "2. DNA polymerase 활성 보조 (sliding clamp 역할)" },
    { "id": 601, "chapter": [12], "professor": "김성찬", "exam": "3차", "question": "ER과 golgi를 거쳐서 sorting 되는 단백질들의 최종 목적지는 어디인가? (*3가지 답하기)", "answer": "plasma membrane, secretory vesicle, lysosome" },
    { "id": 602, "chapter": [13], "professor": "김성찬", "exam": "3차", "question": "In the liver, (peroxisomes) is involved in synthesis of bile acids from cholesterol.", "answer": "peroxisomes" },
    { "id": 701, "chapter": [14], "professor": "박재봉", "exam": "3차", "question": "항암제 taxol의 기능으로 옳은 것은?", "answer": "2. MT(Microtubule) polymer를 안정화시킨다..." },
    { "id": 801, "chapter": [11], "professor": "이규영", "exam": "3차", "question": "nucleus에 대한 설명으로 옳은 것은?", "answer": "3. mRNA processing이 일어나는 곳이다." },
    { "id": 901, "chapter": [17], "professor": "김재봉", "exam": "4차", "question": "Intracellular receptor에 반응하는 small hydrophobic molecule 4종류는?", "answer": "Steroid hormones, Thyroid hormones, Vitamin D3, Retinoic acids" },
    { "id": 902, "chapter": [17], "professor": "김재봉", "exam": "4차", "question": "Ras/Raf/MEK/ERK pathway의 구성 요소를 순서대로 나열하시오.", "answer": "Ras -> Raf -> MEK -> ERK -> Elk-1" },
    { "id": 1001, "chapter": [16], "professor": "박재봉", "exam": "4차", "question": "Neutrophil과 macrophage가 혈관 밖으로 이동하는 과정(extravasation)에 대한 설명으로 옳지 않은 것은?", "answer": "5. Cadherin이 이 세포들과 주변의 세포들을 이어주어 이동을 촉진시킨다..." },
    { "id": 1101, "chapter": [18], "professor": "이규영", "exam": "4차", "question": "세포주기(Cell Cycle)에 대한 설명으로 옳은 것은?", "answer": "4. Interphase(간기)는 G1, S, G2 phase로 나눠진다." },
    { "id": 1102, "chapter": [20], "professor": "이규영", "exam": "4차", "question": "악성 골 종양(malignant bone tumor)이 속하는 암의 종류는?", "answer": "2. Sarcomas (육종)" }
];

const aiQuestionData = [
    { "id": "ai_101", "chapter": [1], "professor": "김성찬", "question": "현미경 기술 중, 살아있는 세포의 특정 단백질 이동을 관찰하는 데 가장 적합한 방법과 그 원리를 서술하시오.", "answer": "방법: 형광 현미경(Fluorescence microscopy)과 GFP(Green Fluorescent Protein) 융합 단백질 기술.\n원리: 관찰하고자 하는 단백질의 유전자에 GFP 유전자를 융합하여 세포 내에서 발현시킨다..." },
    { "id": "ai_201", "chapter": [2], "professor": "김재봉", "question": "인지질(Phospholipid)이 세포막의 기본 구조를 형성하는 핵심적인 화학적 특성은 무엇이며, 이 특성이 수용액 환경에서 어떻게 이중층(bilayer)을 형성하게 하는지 설명하시오.", "answer": "핵심 특성: 양친매성(Amphipathic).\n설명: 인지질은 친수성(hydrophilic) 머리와 소수성(hydrophobic) 꼬리를 동시에 가지고 있다..." },
    { "id": "ai_301", "chapter": [3], "professor": "김재봉", "question": "해당과정(Glycolysis)에서 ATP를 소모하는 단계와 생성하는 단계를 각각 하나씩 들고, 각 단계에 관여하는 효소의 이름을 쓰시오.", "answer": "ATP 소모 단계(Energy Investment Phase):\n- 단계: Glucose → Glucose-6-phosphate\n- 효소: Hexokinase\n\nATP 생성 단계(Energy Payoff Phase):\n- 단계: 1,3-Bisphosphoglycerate → 3-Phosphoglycerate\n- 효소: Phosphoglycerate kinase" }
];